### ISSUE TITLE
模板代码出现#，velocity渲染出错

### ISSUE THREAD

**Issue by Ccupidr** [ballcat-projects/ballcat-codegen#19]
分支：1.4.0
模板文件：
#macro#####################
macro.table.banner={0} record(s) on {1} page(s)
#lables######################
view.lable.search=Search
view.lable.reset=Reset
#controller-message####

错误详情：org.apache.velocity.exception.ParseErrorException: A macro declaration requires at least a name argument at velocityTemplateEngine[line 1, column 1]

**Comment by Hccake** [comment]
特殊字符在模板中需要转义，可以查下 velocity 相关文档

**Comment by Hccake** [comment]
https://velocity.apache.org/engine/devel/user-guide.html



Alternately, the #[[don't parse me!]]# syntax allows the template designer to easily use large chunks of uninterpreted and unparsed content in VTL code. This can be especially useful in place of escaping multiple directives or escaping sections which have content that would otherwise be invalid (and thus unparseable) VTL.
